project:
  type: website
  output-dir: _site
  render:
    - "**/*.qmd"
    - "**/*.md"
    - "!research/CONFERENCE_README.md"
    - "!**/README.md"

website:
  title: "McPherson Lab"
  favicon: images/logo.ico
  description: "Research Group Website"
  navbar:
    background: primary
    search: true
    logo: images/logo.svg
    left:
      - href: about/index.qmd
        icon: info-circle
        text: About
      - href: education/index.qmd
        icon: mortarboard
        text: Education
      - href: research/index.qmd
        icon: graph-up
        text: Research
      - href: technology/index.qmd
        icon: lightbulb
        text: Technology
      - href: publications/index.qmd
        icon: vector-pen
        text: Publications
      - icon: people
        text: People
        href: people/index.qmd
      - icon: person-plus
        href: people/join.qmd
        text: Join

    right:
      - icon: images
        href: gallery/index.qmd
        aria-label: Gallery
      - icon: github
        href: https://github.com/McPhersonLab
        aria-label: GitHub
      - icon: cash-coin
        href: https://simpler.grants.gov/
        aria-label: Grants
      # - icon: hourglass-split
      #   href: https://www.era.nih.gov/
      #   aria-label: eRA
      # - icon: hourglass-bottom
      #   href: https://public.era.nih.gov/assist/
      #   aria-label: Assist
      - icon: clouds
        href: https://zenodo.org/communities/mcphersonlab/
        aria-label: Zenodo
      - icon: cloud-check
        href: https://figshare.com/authors/Jacob_McPherson/23126380
        aria-label: FigShare
      - icon: vector-pen
        href: https://www.scopus.com/authid/detail.uri?authorId=57204192355
        aria-label: SCOPUS
      - icon: book
        href: https://www.webofscience.com/wos/author/record/OZF-0932-2025
        aria-label: WOS
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=MsZPCoIAAAAJ&hl=en
        aria-label: Google Scholar
      - icon: envelope
        href: mailto:jacobmcpherson@utexas.edu
        aria-label: Email
      - icon: calendar-date
        href: https://calendar.app.google/hFWaGJn7qYa74EYaA
        aria-label: Calendar
      - icon: building
        href: https://jacobkmcpherson.com/
        aria-label: Business
      - icon: bluesky
        href: https://bsky.app/profile/jacobkmcpherson.bsky.social
        aria-label: BlueSky
      - icon: twitter
        href: https://x.com/JacobKMcPherson/
        aria-label: Twitter
      - icon: linkedin
        href: https://linkedin.com/in/jacobkmcpherson/
        aria-label: LinkedIn

  page-footer:
    left: "Copyright Â© 2025 Jacob K. McPherson, PharmD, PhD - All Rights Reserved"
    right: 
      - text: "License"
        href: LICENSE.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body:
      - text: |
          <script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
          <script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
